In [7]:
#indexing and slicing in numpy 
import numpy as np
arr=np.array([10,20,30,40])
print(arr[0]) #element index 0 
print(arr[2]) #elemet index 2


10
30


In [2]:
#negative indexing 
print(arr[-1])
print(arr[-2])

40
30


In [ ]:
arr= np.array([12,54,65,78,43])
matrix=np.array([[1,2,3], #0 index
                 [4,5,6], #1 index
                 [7,8,9]]) #2 index
print(matrix[2][2])  #according to python list 

print(matrix[0,0])
print(matrix[0,1])
print(matrix[0,2])
print(matrix[1,0])
print(matrix[1,1])

9
1
2
3
4
5


In [4]:
#slicing
A="Netra"
print(A[::-1])
print(A[:3])

arteN
Net


In [5]:
arr=np.array([0,10,20,30,40,50])
print("slice 1:4: ", arr[::-1])
print("slice with step 2: ", arr[2:5:2])
print("slice with step 2: ", arr[::2])

slice 1:4:  [50 40 30 20 10  0]
slice with step 2:  [20 40]
slice with step 2:  [ 0 20 40]


In [18]:
#first row than coloum 
a =np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
print("submatrix: \n", a[0:2, 1:3])
print("submatrix: \n", a[1:3, 0:2])
print("submatrix: \n", a[2:3, 1:3])
print("submatrix: \n", a[1:3, 1:3])


submatrix: 
 [[2 3]
 [5 6]]
submatrix: 
 [[4 5]
 [7 8]]
submatrix: 
 [[8 9]]
submatrix: 
 [[5 6]
 [8 9]]


In [19]:
arr = np.array([5,10,15,20])
print("elemet > 10: ", arr>10)
print("elemet >10: ", arr[arr>10])

elemet > 10:  [False False  True  True]
elemet >10:  [15 20]


In [21]:
arr= np.array([5,10,15,20])
#indices = np.where(arr>11)
#print(type(indices))
#print("Indices : ", indices)
print("indices : ", np.where(arr>11))
#print("values : ", arr[indices])
print("values: ",arr[np.where(arr>11)])


indices :  (array([2, 3]),)
values:  [15 20]
