In [1]:
import numpy as np 
# np.unique --- unique element remove duplicates 
arr=np.array([1,2,2,3,3,3,4,4,5,5])
unique_values=np.unique(arr)
print("Orginial values:\n",arr)
print("Unique values:\n",unique_values)

Orginial values:
 [1 2 2 3 3 3 4 4 5 5]
Unique values:
 [1 2 3 4 5]


In [2]:
arr=np.array([40,20,10,30])
sorted_values=np.sort(arr)
print("orginal values:\n",arr)
print("sorted values:\n",sorted_values)

orginal values:
 [40 20 10 30]
sorted values:
 [10 20 30 40]


In [4]:
#arg sort write indexies according to orginal array 
arr=np.array([30,10,50,20])
sorted_arr=np.sort(arr)
indices=np.argsort(arr)
print("Array:\n",arr)
print("indices:\n",indices)
print("Sorted using indices:\n",arr[indices])

Array:
 [30 10 50 20]
indices:
 [1 3 0 2]
Sorted using indices:
 [10 20 30 50]


In [ ]:
# where is give the indices of elemet that are true according to the condition 

In [ ]:
#non-zero is the one that write indices of the non-zero            
arr=np.array([0,1,0,2,0,3,0])
print("arrya:\n",arr)
non_zero=np.nonzero(arr)
print("Indices of the non_zero\n",non_zero)
print("Number through indices\n",arr[non_zero])

In [ ]:
arr=np.array([5,10,11])
print("Any element greater than 10:",np.any(arr<5)) #if any true write true
print("All element greater than 10:",np.all(arr>4)) #if any false write false

Any element greater than 10: True
All element greater than 10: True


In [ ]:
arr=np.array([1,np.nan,np.inf,-np.inf,5])
print("Array:\n",arr)
print("Isnan:\n",np.isnan(arr)) # only write true when there is nan 
print("isinf:\n",np.isinf(arr)) # positive infite and negative infite write true 
print("isinfinte:\n",np.isfinite(arr)) # true when there is number 

Array:
 [  1.  nan  inf -inf   5.]
Isnan:
 [False  True False False False]
isinf:
 [False False  True  True False]
isinfinte:
 [ True False False False  True]


In [4]:
arr=np.array([10,20,np.nan,40])
print("Array:\n",arr)
print("mean(normal):\n",np.mean(arr))
print("mean ignoring NaN:\n",np.nanmean(arr))
print("Standard deviation ignoring NaN:\n",np.nanstd(arr))
print("Sum ignoring NaN:\n",np.nansum(arr))


Array:
 [10. 20. nan 40.]
mean(normal):
 nan
mean ignoring NaN:
 23.333333333333332
Standard deviation ignoring NaN:
 12.472191289246473
Sum ignoring NaN:
 70.0


In [5]:
#clip - give min and max value - convert that into given range 
arr=np.array([2,5,10,9,11,15,20])
clipped=np.clip(arr,8,12)
print("original Array:",arr)
print("Clipped Array:",clipped)

original Array: [ 2  5 10  9 11 15 20]
Clipped Array: [ 8  8 10  9 11 12 12]
