In [4]:
import numpy as np
# elemet and aggragtion 
# element 
a = np.array([10,20,30])
b= np.array([2,4,5])
print(a+b)  #add
print(a-b) #sub
print(a*b)  # multi
print(a/b) # division
print(a//b) #floor division
print(a**b) # power
print(a%b) #modulus

[12 24 35]
[ 8 16 25]
[ 20  80 150]
[5. 5. 6.]
[5 5 6]
[     100   160000 24300000]
[0 0 0]


In [ ]:
#comparison operators 
a=np.array([5,10,15])
print (a<8) #greater than 8
print(a[a>8]) #greater than 8 
print(a==10) #equal to 10
print(a!=8) #not equal to


[ True False False]
[10 15]
[False  True False]
[ True  True  True]


In [5]:
#logical operators 
a= np.array([5,8,15,20])
cond1 = a>8
cond2 =a<18

print(np.logical_and(cond1,cond2)) # correct any one condition true write true 
print(a[np.logical_and(cond1,cond2)])
print(np.logical_or(cond1,cond2)) #either of condition is true write true or else false
print(a[np.logical_or(cond1,cond2)])
print(np.logical_not(cond1)) # write opposite of the answer 
print(a[np.logical_not(cond1)])

[False False  True False]
[15]
[ True  True  True  True]
[ 5  8 15 20]
[ True  True False False]
[5 8]


In [ ]:
#elemet-wise vs aggregate 
arr = np.array([1,2,3,4])
print(arr**2) #elemet wise each element in erray 
print(np.sum(arr)) #aggregate

[ 1  4  9 16]
10


In [7]:
a=np.array([4,9,16])
b=np.array([2,3,4])
c=np.array([2,8,4])

print(np.add(a,b)) #add
z=np.add(a,b)
print(np.add(z,c))
print(np.subtract(a,b)) #sub
print(np.divide(a,b)) #divide
print(np.power(a,2)) #power 
print(np.mod(a,b)) #module
print(np.sqrt(a)) #square root
print(np.exp(a)) #exponential
print(np.log(a)) #natural log
print(np.log10(a)) #log base 10

[ 6 12 20]
[ 8 20 24]
[ 2  6 12]
[2. 3. 4.]
[ 16  81 256]
[0 0 0]
[2. 3. 4.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]
[1.38629436 2.19722458 2.77258872]
[0.60205999 0.95424251 1.20411998]


In [8]:
arr=np.array([1.5,2.6,3.2])
print(np.round(arr)) #round
print(np.floor(arr)) #floor
print(np.ceil(arr)) #ceil


[2. 3. 3.]
[1. 2. 3.]
[2. 3. 4.]


In [9]:
#statistical operation 
data=np.array([10,24,30,36,50])
print(np.mean(data)) #mean
print(np.median(data)) #median 
print(np.std(data)) #if we want the in normal of variance so use STANDARD DEVIATION
print(np.var(data)) #how far the data is from mean as square  VARIANCE
print(np.min(data)) #minimum
print(np.max(data)) #max
print(np.sum(data)) #sum
print(np.cumsum(data)) #cumulative sum  do sum like 1,2,3,4 = 1,1+2=3,3+2=5,5+4=9
print(np.prod(data)) #product it is kind of multiplication
print(np.percentile(data,90)) #90th percentile 

30.0
30.0
13.206059215375342
174.4
10
50
150
[ 10  34  64 100 150]
12960000
44.4
