In [1]:
# Array manipulation 
# merge = concatenate()
# differenec between plus and coma
# plus add extra space 
print("ABC" + "DEF" + "GHI")
import numpy as np
a = np.array([[1,2],[3,4],[11,12]])
print("Normal \n", a)
b=np.array([[5,6],[7,8],[11,12]]) 
print("Normal \n",b)
c=np.array([[9,10],[11,12],[11,12]])
print("Normal \n",c)

print("Concatenate \n", np.concatenate((a,b,c)))
print("Concatenate axis=0: \n", np.concatenate((a,b,c), axis=0))
print("Concatenate axis=1: \n", np.concatenate((a,b,c), axis=1))
 

ABCDEFGHI
Normal 
 [[ 1  2]
 [ 3  4]
 [11 12]]
Normal 
 [[ 5  6]
 [ 7  8]
 [11 12]]
Normal 
 [[ 9 10]
 [11 12]
 [11 12]]
Concatenate 
 [[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]
 [ 7  8]
 [11 12]
 [ 9 10]
 [11 12]
 [11 12]]
Concatenate axis=0: 
 [[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]
 [ 7  8]
 [11 12]
 [ 9 10]
 [11 12]
 [11 12]]
Concatenate axis=1: 
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]
 [11 12 11 12 11 12]]


In [2]:
#stacking functions
print("Vstack:\n",np.vstack((a,b,c)))
print("Hstack:\n",np.hstack((a,b,c)))
print("Dstack:\n",np.dstack((a,b,c)))

Vstack:
 [[ 1  2]
 [ 3  4]
 [11 12]
 [ 5  6]
 [ 7  8]
 [11 12]
 [ 9 10]
 [11 12]
 [11 12]]
Hstack:
 [[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]
 [11 12 11 12 11 12]]
Dstack:
 [[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]

 [[11 11 11]
  [12 12 12]]]


In [3]:
A=np.array([2,4,5,True,False])
B=np.array([2,4,5.7,True,"Netra"])
print(A)
print(B)

[2 4 5 1 0]
['2' '4' '5.7' 'True' 'Netra']


In [4]:
#smallest boolena,int,float,strng--strongest
#if we want t o split array into equally to use np.split
arr=np.arange(12)
print(arr)
print("Split:",np.split(arr,3)) #if possible than only split or error
print("Array Split:",np.array_split(arr,4)) #can split anything in worst cases


[ 0  1  2  3  4  5  6  7  8  9 10 11]
Split: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
Array Split: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [ ]:
#insert,append,delete
arr=np.array([])

In [5]:
arr=np.array([1,2,3])
view_Arr=arr.view()
copy_arr=arr.copy()
arr[0]=100
print("orignal:",arr)
print("View:",view_Arr)
print("copy:",copy_arr)

orignal: [100   2   3]
View: [100   2   3]
copy: [1 2 3]
