In [1]:
import numpy as np

arr = np.array([5,10,15,20])
print("Numpy Array: ", arr) 

Numpy Array:  [ 5 10 15 20]


In [3]:
Arange = np.arange(0,19,3)
print("Arange: ", Arange)

Arange:  [ 0  3  6  9 12 15 18]


In [5]:
Space = np.linspace(1,3,6)
print("Equally Spaced Between 1 to 3 is: ", Space)

Equally Spaced Between 1 to 3 is:  [1.  1.4 1.8 2.2 2.6 3. ]


In [7]:
zero = np.zeros([2,4])
print("Zeros of matrix 2*4: ", zero)

Zeros of matrix 2*4:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
ones = np.ones([3,3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
Uniform = np.random.rand(2,2)
print("Random Uniform: ", Uniform)

Random Uniform:  [[0.17805976 0.59499296]
 [0.42923894 0.29824913]]


In [11]:
identity = np.identity(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
arr = np.array([[1,2,3],[4,5,6]])
print("Size: ", arr.size)
print("Shape: ",arr.shape) 
print("Number of Dimensions: ", arr.ndim)

Size:  6
Shape:  (2, 3)
Number of Dimensions:  2
