In [1]:
import numpy as np
arr=np.arange(15)
print("Split:",np.split(arr,5)) 

Split: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11]), array([12, 13, 14])]


In [7]:
arr=np.arange(12)
print("Array Split: \n",np.array_split(arr,4))

Array Split: 
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]


In [8]:
arr=np.array([10,20,30,40,50])
print("Insert:\n",np.insert(arr,2,25))

Insert:
 [10 20 25 30 40 50]


In [9]:
arr=np.array([[1,2],[3,4]])
print("Insert:\n",np.insert(arr,1,[5,6]))

Insert:
 [1 5 6 2 3 4]


In [ ]:
arr=np.array([5,10,15])
print("Append:\n",np.append(arr,[20,25]))

Insert:
 [ 5 10 15 20 25]


In [11]:
arr=np.array([[1,2],[3,4]])
print("Append:\n",np.append(arr,[7,8]))

Append:
 [1 2 3 4 7 8]


In [16]:
arr=np.array([100,200,300,400,500])
print("Delete:\n",np.delete(arr,3))
print("Delete:\n",np.delete(arr,[0,1]))

Delete:
 [100 200 300 500]
Delete:
 [300 400 500]


In [18]:
arr=np.array([[1,2],[3,4],[5,6]])
print("Delete 2 ROW:\n",np.delete(arr,1,axis=0))

Delete 2 ROW:
 [[1 2]
 [5 6]]


In [20]:
arr=np.array([1,2,3,4])
view_arr=arr.view()
copy_arr=arr.copy()
view_arr[0]=999
print("Orginial:\n",arr)
print("View:\n",view_arr)
print("Copy:\n",copy_arr)

Orginial:
 [999   2   3   4]
View:
 [999   2   3   4]
Copy:
 [1 2 3 4]


In [27]:
arr=np.arange(1,7)
arr = arr.reshape(2, 3)
arr[0,1]=100 
print(arr)


[[  1 100   3]
 [  4   5   6]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
faltten=arr.flatten()
ravel=arr.ravel()
faltten[0]=100
ravel[0]=200
print("Flatten:\n",faltten)
print("Ravel:\n",ravel)


Flatten:
 [100   2   3   4   5   6]
Ravel:
 [  1 200   3   4   5   6]


In [3]:
arr=np.arange(1,13)
print("Split:\n",np.split(arr,3))
n=np.split(arr,3)
print("Delete:\n",np.delete(arr,3,axis=1))

Split:
 [array([1, 2, 3, 4]), array([5, 6, 7, 8]), array([ 9, 10, 11, 12])]


AxisError: axis 1 is out of bounds for array of dimension 1