In [3]:
import numpy as np

arr=np.arange(1,13)
print(arr)
reshaped = arr.reshape(3,4)
print("Reshaped arr: ", reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped arr:  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [9]:
Matrix =np.arange(1,17)
print("Normal Matrix: \n", Matrix)
print("Transope using T: \n", Matrix.T)
print("Transope using function: \n", np.transpose(Matrix))

Normal Matrix: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Transope using T: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
Transope using function: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [11]:
Linespace = np.linspace(10,30,5)
print("Line space between 10 to 30 are: \n", Linespace)

Line space between 10 to 30 are: 
 [10. 15. 20. 25. 30.]


In [13]:
Arr = np.random.randint(10,50, (3,3))
print("Random Interger: \n", Arr)

Random Interger: 
 [[19 33 26]
 [27 14 37]
 [35 10 13]]


In [17]:
Matrix = np.random.randn(2,5)
print ("Normal: \n", Matrix )
print("\n dtype: \n", Matrix.dtype)
print("\n itemsize: \n", Matrix.itemsize)

Normal: 
 [[-1.43667407  0.6227964  -1.33732077 -0.30026333  0.12163338]
 [-0.20865206 -0.65208773  1.28152699 -0.19320701 -0.37273599]]

 dtype: 
 float64

 itemsize: 
 8


In [ ]:


Arr = np.arange(1,10) 
print ("Normal: \n", Arr)
print ("\n Ravel: \n", Arr.ravel())
print ("\n Flatten: \n", Arr.flatten())


Normal: 
 [1 2 3 4 5 6 7 8 9]

 Ravel: 
 [1 2 3 4 5 6 7 8 9]

 Flatten: 
 [1 2 3 4 5 6 7 8 9]


In [6]:
matrix = np.empty((3,7))
print("Normal: \n", matrix)
print ("Transpose using: \n", matrix.T)


Normal: 
 [[6.11624228e-297 6.95314710e-310 0.00000000e+000 6.95314710e-310
  3.89387925e-308 0.00000000e+000 0.00000000e+000]
 [4.24399158e-311 2.12199579e-311 4.94065646e-321 0.00000000e+000
  2.47032823e-323 0.00000000e+000 6.69756969e-312]
 [6.69756424e-312 3.89387925e-308 0.00000000e+000 0.00000000e+000
  6.56725888e-288 0.00000000e+000 0.00000000e+000]]
Transpose using: 
 [[6.11624228e-297 4.24399158e-311 6.69756424e-312]
 [6.95314710e-310 2.12199579e-311 3.89387925e-308]
 [0.00000000e+000 4.94065646e-321 0.00000000e+000]
 [6.95314710e-310 0.00000000e+000 0.00000000e+000]
 [3.89387925e-308 2.47032823e-323 6.56725888e-288]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.69756969e-312 0.00000000e+000]]
