In [2]:
import numpy as np
Netra = np.array([8000, 9000, 7500, 10000, 8500, 9500, 11000])
Krish = np.array([7000, 8500, 8000, 9500, 9000, 10000, 10500])
print("Friend 1:", Netra, "\nFriend 2:", Krish)
print("\nAddition:")
print(Netra + Krish)

print("\nSubtraction:")
print(Netra- Krish)

print("\nMultiplication:")
print(Netra * Krish)

print("\nDivision:")
print(Netra / Krish)



Friend 1: [ 8000  9000  7500 10000  8500  9500 11000] 
Friend 2: [ 7000  8500  8000  9500  9000 10000 10500]

Addition:
[15000 17500 15500 19500 17500 19500 21500]

Subtraction:
[1000  500 -500  500 -500 -500  500]

Multiplication:
[ 56000000  76500000  60000000  95000000  76500000  95000000 115500000]

Division:
[1.14285714 1.05882353 0.9375     1.05263158 0.94444444 0.95
 1.04761905]


In [2]:
preferences = np.array([
    [5, 3, 4],
    [2, 4, 5],
    [3, 5, 2]
])

popularity = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
recommendation1 = np.dot(preferences, popularity)
recommendation2 = np.matmul(preferences, popularity)
print("Matrix Recommendation of Dot:", recommendation1, "\nMatrix Recommendation of matmul:", recommendation2)

Matrix Recommendation of Dot: [[45 57 69]
 [53 64 75]
 [37 47 57]] 
Matrix Recommendation of matmul: [[45 57 69]
 [53 64 75]
 [37 47 57]]


In [3]:
image = np.array([
    [120, 130, 125, 140],
    [110, 115, 135, 145],
    [100, 105, 150, 155],
    [90, 95, 160, 170]
])
print("Original Image:",image)
rotated=image.T 
print("\nTranspose image:",rotated)
print("\nMean:",np.mean(image), "\nMedian:",np.median(image), "\nStandard Deviation:", np.std(image), "\nVariance:", np.var(image))


Original Image: [[120 130 125 140]
 [110 115 135 145]
 [100 105 150 155]
 [ 90  95 160 170]]

Transpose image: [[120 110 100  90]
 [130 115 105  95]
 [125 135 150 160]
 [140 145 155 170]]

Mean: 127.8125 
Median: 127.5 
Standard Deviation: 23.58288243090738 
Variance: 556.15234375


In [4]:
matrix = np.array([
    [4, 2, 1],
    [2, 5, 3],
    [1, 3, 6]
])
print("Matrix:",matrix)
print("\nDeterminant:", np.linalg.det(matrix), "\nInverse:",np.linalg.inv(matrix), "\nEigenvalues:",np.linalg.eig(matrix), 
      "\nEigenvectors:", np.linalg.eig(matrix))


Matrix: [[4 2 1]
 [2 5 3]
 [1 3 6]]

Determinant: 66.99999999999997 
Inverse: [[ 0.31343284 -0.13432836  0.01492537]
 [-0.13432836  0.34328358 -0.14925373]
 [ 0.01492537 -0.14925373  0.23880597]] 
Eigenvalues: EigResult(eigenvalues=array([9.34849393+0.j, 3.73015912+0.j, 1.92134694+0.j]), eigenvectors=array([[-0.3650547 +0.j, -0.77587586+0.j,  0.5145403 +0.j],
       [-0.63657455+0.j, -0.19527095+0.j, -0.74608451+0.j],
       [-0.67934373+0.j,  0.59990492+0.j,  0.42261825+0.j]])) 
Eigenvectors: EigResult(eigenvalues=array([9.34849393+0.j, 3.73015912+0.j, 1.92134694+0.j]), eigenvectors=array([[-0.3650547 +0.j, -0.77587586+0.j,  0.5145403 +0.j],
       [-0.63657455+0.j, -0.19527095+0.j, -0.74608451+0.j],
       [-0.67934373+0.j,  0.59990492+0.j,  0.42261825+0.j]]))


In [5]:
orders = np.array([
    [120, 140, 150, 160, 170, 180],
    [110, 130, 145, 155, 165, 175]
])
print("Original Array:", orders)
reshaped = orders.reshape(3, 4)
print("\nReshaped (3x4):", reshaped)
flattened = reshaped.flatten()
print("\nFlattened Array:",flattened)
part1, part2 = np.split(flattened, 2)
print("\nPart 1:", part1)
print("\nPart 2:", part2)
stacked = np.vstack((part1, part2))
print("\nVertically Stacked:", stacked)


Original Array: [[120 140 150 160 170 180]
 [110 130 145 155 165 175]]

Reshaped (3x4): [[120 140 150 160]
 [170 180 110 130]
 [145 155 165 175]]

Flattened Array: [120 140 150 160 170 180 110 130 145 155 165 175]

Part 1: [120 140 150 160 170 180]

Part 2: [110 130 145 155 165 175]

Vertically Stacked: [[120 140 150 160 170 180]
 [110 130 145 155 165 175]]
