In [1]:
import numpy as np
followers = np.array([1200,64000,15000,320000,1250000])
print("Followers Array:", followers)
print("Shape:",followers.shape)
print("Number of Dimensions:", followers.ndim)
print("Data type:",followers.dtype)


Followers Array: [   1200   64000   15000  320000 1250000]
Shape: (5,)
Number of Dimensions: 1
Data type: int64


In [2]:
order_ids = np.arange(101, 111)
print("Order IDs:", order_ids)
print("Size:", order_ids.size)

Order IDs: [101 102 103 104 105 106 107 108 109 110]
Size: 10


In [3]:
like_matrix = np.eye(3)
print("Identity Matrix:")
print(like_matrix)

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
scores = [45, 67, 120, 89, 54]
scores_array = np.array(scores)
print("Cricket Scores:", scores_array)
print("Item Size:", scores_array.itemsize, "bytes")

Cricket Scores: [ 45  67 120  89  54]
Item Size: 8 bytes
